# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "Orienteringsløb"
  pageRef = "introloeb"
  weight = 5

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 30

# -- Footer Menu --

[[footer]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[footer]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[footer]]
  name = "Contact"
  pageRef = "contact"
  weight = 30
